name: Publish Python AWS SAM

on: 
  push:
    branches:
      - main
    paths:
        - 'kjell/**' 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: aws-actions/setup-sam@v1
    
    - name: Install Dependencies
      run: pip install -r ./kjell/hello_world/requirements.txt

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Build SAM Application
      run: sam build --use-container
      working-directory: ./kjell

    - name: Deploy SAM application
      run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name kandidat2033 --capabilities CAPABILITY_IAM --resolve-s3
      working-directory: ./kjell
